trigger:
- main

pool:
  name: mac

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -DskipTests=true'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Maven
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Shopping'
    publishLocation: 'Container'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'local-sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'shopping-cart'
    cliProjectName: 'shopping-cart'
    cliSources: '.'
    extraProperties: 'sonar.java.binaries=.'
    
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

#- task: dependency-check-build-task@6
#  inputs:
#    projectName: 'ShoppingCart'
#    scanPath: '.'
#    format: 'HTML'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker build -t shopping1.0:latest -f docker/Dockerfile .'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker run -d --name shop -p 8070:8070 shopping1.0:latest'
